### ISSUE TITLE
script标签 加载 https://unpkg.com/hel-micro@4.9.11/dist/hel-micro.js 引入使用

### ISSUE THREAD

**Issue by zhangbinzhbb** [Tencent/hel#102]
1、https://unpkg.com/hel-micro@4.9.11/dist/hel-micro.js
2、https://unpkg.com/browse/hel-micro-core@4.9.2/lib/index.js   

下图截图报错
![1cc1a7ba19af5d7d840adb0db62af99](https://github.com/user-attachments/assets/7b2bb285-8fc1-4047-b508-b856ee130271)
![c792e5ad07aae1aff36861c79ad69e3](https://github.com/user-attachments/assets/36ecc7f5-e782-4f80-ad22-7f789221af6b)

**Comment by fantasticsoul** [comment]
core 使用dist 目录的即可
https://unpkg.com/browse/hel-micro-core@4.9.2/dist/hel-micro-core.js
