### ISSUE TITLE
hel-micro本地运行 getCodeHost方法抛出的异常

### ISSUE THREAD

**Issue by xuzhijiegithub** [Tencent/hel#85]
按照文档，发布到本机启动的nginx上
![0a029fd21cb1dd890634c96232e69cb](https://github.com/Tencent/hel/assets/87740340/15c2ab6a-bfc7-429f-8b3b-3139f4e5ff9f)
，然后这边加载对应的路径，然后运行的时候报这个错
![09f29cc6c05347dbca047a3c605e476](https://github.com/Tencent/hel/assets/87740340/856c6925-f1ee-42c2-9457-9a482354a4d4)
![8d63b94906eb6762a78954b8190b412](https://github.com/Tencent/hel/assets/87740340/f32ae8ad-5bec-4ae2-ab3c-3bb998272d9d)

**Comment by fantasticsoul** [comment]
进了解发现是这个示例出现的 https://github.com/hel-eco/hel-tpl-remote-vue-comp/blob/master/package.json 里面的 hel-iso 版本过旧，升级到最新 hel-iso 4.3.4 即可

<img width="1598" alt="image" src="https://github.com/Tencent/hel/assets/7334950/1bc00ccb-0a5f-47af-bd36-e19277dabed0">
