### ISSUE TITLE
hel-micro with preFetchLib catch on 404 or other status

### ISSUE THREAD

**Issue by MrV-777** [Tencent/hel#88]
First want to thank for nice micro framework. 

I tried to use in **vue3 with hel-micro**, but didn't find how to catch if remote service down or any reason page response 404 and display other warning message for other component versus display on browser alert message.

here is part of **vue3 sample** I used:

```vue
<template>
  <RemoteComp msg="Welcome to Your Vue.js + TypeScript + hel-micro App" />
</template>

<script lang="js">
import { preFetchLib } from 'hel-micro';
import { defineAsyncComponent } from 'vue';

export default {
  name: 'HelloWorld',
  components: {
     RemoteComp: defineAsyncComponent({
      loader: async () => {

        // component name + remote url
        const mod = await preFetchLib('hel-tpl-remote-vue3-comps-ts', {
          custom: {
            host: 'https://unpkg.com/hel-tpl-remote-vue3-comps-ts/hel_dist/'
          },
          enableDiskCache: true
        });

        //const mod = await preFetchLib("hel-tpl-remote-vue3-comps-ts");
        return mod.HelloWorld;
      },
    }),
  },
}
</script>
```

if url was down I want to display another inside component versus exceptions, does that **preFetchLib** function support catch?

Thanks

**Comment by fantasticsoul** [comment]
you can read the doc of [defineAsyncComponent](https://vuejs.org/guide/components/async.html)，use `errorComponent ` , `loadingComponent` to resolve your problem.

here is a online [demo](https://codesandbox.io/p/sandbox/demo-load-remote-vue3-comp-lazy-forked-93nsyn)

but currently I can not get err ref or err message string in the ErrComponent, so I post a [issue](https://github.com/vuejs/core/issues/9714) to vue3 repo.

**Comment by Alfred-Skyblue** [comment]
`errorComponent` receives an `error` prop. You should modify the code accordingly:

```ts
export default {
  name: "ErrorComponent",
    props: {
      error: Error,
    },
};
```

[playground](https://play.vuejs.org/#eNqFU01v2zAM/SuELnYAwwnWW5YE6IYetsNWbL3NOxg2nSq1JUMfSQrD/72klDpBkbY2YIjkE/nIRw/itu/zvUexFCtbGdk7sOh8vymU7HptHAxQYyMV3tpnVX3X5FSoXHbyXjgeMzDYwAiN0R0klDSZkjDs5M/nbHDN5Guh4tt4VTmpFbS6rKeU6WzgIFBa540ChQe4pxzSYpoatLrdY2Zwh5WbrTeEBXqI/YPsUHuXpmcv52BcmnAFQGO0SWYxNmZfFotFMEb6jlyz0so6mFqG9dUhpCE7Z0SzhJJjkM5gvYFY9sS7PJTSvW0tlMv4G8hMkWWYFdEgxGoeJSExyHDY9W3pkCyA1cRks5qfz3xnwolMOEudNHKb76xWpHHgVYiKsLJF87vnqdtCLE+MKVa2rT78DD5nPAaK4c4jVk9X/Dt7ZF8h7kkSNHssxBRzpdmii+G7v7/wSOcp2Onat4T+IPiHRfbMMcK+eVUT7QtcYPsjLJlU2wd7d3So7GtTTPQ86ELQ0vGY3mv9TPcmvwn3SAea4uvCXvlJChUXg/ayt+m/JG7W/0/Eq+U+HACGIeqfd2htuUUYqSYh5hFyqeb4AtgGQA4=)

**Comment by MrV-777** [comment]
> you can read the doc of [defineAsyncComponent](https://vuejs.org/guide/components/async.html)，use `errorComponent ` , `loadingComponent` to resolve your problem.
> 
> <img alt="image" width="763" src="https://private-user-images.githubusercontent.com/7334950/286783503-b65f6649-fcb2-4e2e-a725-8eaa0945e77f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjQ1NjAsIm5iZiI6MTcwMTM2NDI2MCwicGF0aCI6Ii83MzM0OTUwLzI4Njc4MzUwMy1iNjVmNjY0OS1mY2IyLTRlMmUtYTcyNS04ZWFhMDk0NWU3N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMTcxMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRlMDc1YTk2YjE1YWNmZGZkZDY0NWE3Yzc2ZDQ0NDFjMDllMDNlMGM2MWZmMDRkZDdkMjVlNWJkZWZjODhkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Milce9G6-bAuy5MXbXHxqLNTcKir2zCMIgbr0Nr18_M">
> you can check this online [demo](https://codesandbox.io/p/sandbox/demo-load-remote-vue3-comp-lazy-forked-93nsyn)

Finally I found a reason why it not worked, it was totally different problem, because I tested all existed options in **preFetchLib** and didn't think that may break something. 
I used custom option called **enable** and set to **false**:
```vue
const mod = await preFetchLib('hel-tpl-remote-vue3-comps-ts', {
      custom: {
        host: uri,
        enable: false
      }
    });
```

and then returned back to **true**, then removed from code. 
Finally I specified incorrect host Uri to test is catch errors working and on the end appeared alert message:

> 

![image](https://github.com/Tencent/hel/assets/81026979/0a1c4443-d86d-412b-8e73-d9ae72d102e4)

and **defineAsyncComponent** fully stopped to work  till not removed manually DB **HelIndexedDB** from browser cache:
![image](https://github.com/Tencent/hel/assets/81026979/6c19c81c-70de-4ed5-815d-67366d101eb6)

That caused to stuck in simple place :) Why that JavaScript popup alert message was added to library maybe authors can answer.

Anyway thanks for help.

**Comment by fantasticsoul** [comment]
at `hel-micro <=4.8.11` version lib，you can write like this to skip reusing cached app meta json.
```ts
await preFetchLib('hel-tpl-remote-vue3-comps-ts', {
      hook: {
          onFetchMetaFailed(){
              // here allow user return a prepared static meta json to let app works well.
              // but if user want to keep throwing error, just return null
               return null;
          }
      }
    });
```

and I also bump `hel-micro` to `4.8.12` to make throwing error easier. (  [commit](https://github.com/Tencent/hel/commits/main) )

at `hel-micro >4.8.12` version lib，you can set `enableDiskCacheForErr=false` to skip reusing cached app meta json.
```ts
await preFetchLib('hel-tpl-remote-vue3-comps-ts', {
      enableDiskCacheForErr: false,
    });
```

**Comment by fantasticsoul** [comment]
close issue
