### ISSUE TITLE
hel-iso在firefox浏览器下 getCodeHost报错loc.split('//')[1].split('/')[0];Uncaught TypeError: e.split(...)[1] is undefined

### ISSUE THREAD

**Issue by qinxiaozhu** [Tencent/hel#89]
是不是不支持firefox

**Comment by fantasticsoul** [comment]
最新版本 `hel-iso` 4.3.4 已解决此问题
![image](https://github.com/Tencent/hel/assets/7334950/0d81f361-6c3c-41c6-a589-c3c36c0f54c6)

你看下你本地的版本多少呢，来自于哪个模板项目呢，我去升级下

**Comment by qinxiaozhu** [comment]
我是4.3.2我去升级一下 谢谢～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月09日 07:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Tencent/hel] hel-iso在firefox浏览器下 getCodeHost报错loc.split('//')[1].split('/')[0];Uncaught TypeError: e.split(...)[1] is undefined (Issue #89) |

最新版本 hel-iso 4.3.4 已解决此问题
image.png (view on web)

你看下你本地的版本多少呢，来自于哪个模板项目呢，我去升级下

**Comment by fantasticsoul** [comment]
已修复
