### ISSUE TITLE
在已有的模板项目中,没有看到vite.config.js相关的,只看到一个特殊处理的vite打包文件的模板

### ISSUE THREAD

**Issue by JohnnyTang-D** [Tencent/hel#91]
请问是否可以出一个关于vite.config.js的模板.
vite4以上以及vue3.4以上版本

**Comment by fantasticsoul** [comment]
这个是一个同事自己搭的例子，你参考试试
https://github.com/chenweifang4/cwf-hel-vite-vue-demo

**Comment by fantasticsoul** [comment]
vite4 vue3 示例已提供
https://github.com/decadef20/hel-lib-vue-comps-vite
