### ISSUE TITLE
主子应用集成加载，import { isMasterApp } from 'hel-iso'，子应用isMasterApp 失效

### ISSUE THREAD

**Issue by zhangbinzhbb** [Tencent/hel#92]
1、主子应用集成加载，子应用 引入import { isMasterApp } from 'hel-iso'，判断是否独立运行，主子加载，子应用还是会走独立运行，isMasterApp 失效
2、当前解决，主应用也需要引入 import 'hel-iso'，子应用isMasterApp 生效

**Comment by zhangbinzhbb** [comment]
![企业微信截图_17059888056142](https://github.com/Tencent/hel/assets/22054556/0a1882a0-9350-47f4-91c0-08ac664541da)

**Comment by fantasticsoul** [comment]
主应用 hel-micro 升级到 4.9.2，子应用的 hel-iso 升级到 4.4.0，应该就没问题了（此时主应用就不需要独立导入 hel-iso 了）

**Comment by fantasticsoul** [comment]
问题已修复
