### ISSUE TITLE
hel远程模块发布npm包路径支持alias识别

### ISSUE THREAD

**Issue by fandywen** [Tencent/hel#93]
目前自己基于hel微模块构建一个远程模块hel-remote-common-module，本地install hel-remote-common-module的时候，本地开发启动项目时候报错，希望hel远程模块发布npm包路径能支持alias识别
 #>
![23443](https://github.com/Tencent/hel/assets/22906355/7ed01e08-e73a-45e9-9db3-f99b274a8252)

```[tasklist]
### Tasks
```

**Comment by fantasticsoul** [comment]
安装最新版本的`replace-absolute-path`，修改srcipts下的[replaceToRelativePath](https://github.com/hel-eco/hel-tpl-remote-react-comp/blob/1.3.5-replace/scripts/replaceToRelativePath.js)脚本的`replacePath`调用里，添加`alias`配置，例如
```
alias: { '@src/hooks':'hooks' }
```

**Comment by fantasticsoul** [comment]
已支持
